name: UI tests VK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      # Установка зависимостей из package.json
      - name: Install deps
        run: npm i

      # Запуск тестов
      - name: Run tests
        run: npm run test
        continue-on-error: true
        env:
          VK_PHONE: ${{ secrets.VK_PHONE }}
          VK_PASSWORD: ${{ secrets.VK_PASSWORD }}
          VK_ID: ${{ secrets.VK_ID }}
