name: UI tests VK

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      # Установка зависимостей из package.json
      - name: Install deps
        run: npm i
      # Запуск тестов
      - name: Run tests
        run: npx playwright test
        continue-on-error: true
        env:
          VK_PHONE: ${{ secrets.VK_PHONE }}
          VK_PASSWORD: ${{ secrets.VK_PASSWORD }}
          VK_ID: ${{ secrets.VK_ID }}
